name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v6
      with:
        node-version: lts/*
    - name: Install dependencies 🛎 
      run: npm ci
    - name: Install Playwright Browsers 🚀
      run: npx playwright install --with-deps
    - name: Run Playwright tests 🧪
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 5
    - name: Deploy to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v4
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: ./playwright-report
    - name: Full Test Report Summary Link
      if: always()
      run: echo "Report URL https://kozinvl.github.io/PlaywrightAutomation/" >> $GITHUB_STEP_SUMMARY
    - name: Publish CTRF Test Summary Results
      run: npx github-actions-ctrf summary ./results.json
      if: always()